services:
  php:
    platform: ${PLATFORM}
    # phpだけはカスタムしたい（composer入れたいとか）ので、buildで追加
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_IMAGE=${PHP_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-web
    depends_on:
      - db
    volumes:
      - ${DOC_ROOT}:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${WEB_PORT}:80

  # php以外はカスタムせず、そのまま入れるのでimageのまんま追加
  db:
    image: ${DB_IMAGE}
    platform: ${PLATFORM}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      ## 永続化する場合は以下をコメントアウト
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    restart: no

  phpmyadmin:
    image: ${PMA_IMAGE}
    platform: ${PLATFORM}
    container_name: ${COMPOSE_PROJECT_NAME}-pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASS}
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: ${MAILHOG_IMAGE}
    platform: ${MAILHOG_PLATFORM}
    ports:
      - ${MAILHOG_PORT1}:1025
      - ${MAILHOG_PORT2}:8025

  atlas-backend:
    platform: ${PLATFORM}
    container_name: ${COMPOSE_PROJECT_NAME}-atlas-backend
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_IMAGE=${PHP_IMAGE}
    ports:
      - ${ATLAS_PORT}:80
    volumes:
      - ../../atlas-backend:/var/www/html

  lamp-ui:
    image: ${LAMP_IMAGE}
    platform: ${LAMP_PLATFORM}
    container_name: ${COMPOSE_PROJECT_NAME}-lamp-ui
    ports:
      - ${LAMP_PORT}:80
    volumes:
      - ${DOC_ROOT_LAMP}:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
