services:
  atlas-app:
    build:
      context: ../../apps/atlas
    container_name: genie-platform-atlas-app
    ports:
      - "9090:80"
    volumes:
      - ../../apps/atlas:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: atlas_db
      DB_USERNAME: atlas_user
      DB_PASSWORD: password

  atlas-ui:
    build:
      context: ../../apps/atlas-ui
    container_name: genie-platform-atlas-ui
    ports:
      - "3001:3000" # Reactアプリ用ポート
    volumes:
      - ../../apps/atlas-ui:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  lamp-app:
    build:
      context: ../../apps/lamp
    container_name: genie-platform-lamp-app
    volumes:
      - ../../apps/lamp:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  lamp-ui:
    build:
      context: ../../apps/lamp-ui
    container_name: genie-platform-lamp-ui
    ports:
      - "3000:3000"
    volumes:
      - ../../apps/lamp-ui:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  nginx:
    image: nginx:stable
    container_name: genie-platform-nginx
    ports:
      - "8080:80"
    volumes:
      - ../../apps/lamp/public:/var/www/html/public
      - ../../apps/lamp-ui/build:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
      - ./phpmyadmin/sessions:/sessions
    depends_on:
      - lamp-app
      - lamp-ui

  mysql:
    image: mysql:8
    container_name: genie-platform-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genie
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: ${PMA_IMAGE}
    container_name: genie-platform-phpmyadmin
    platform: ${PLATFORM}
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASS}
    depends_on:
      - mysql
    volumes:
      - ./phpmyadmin/sessions:/sessions
      - ./infra/mysql/initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
