# infra/docker-compose.yml

version: "3.8"
services:
  lamp-app:
    build:
      context: ../../apps/lamp # ← genie-platform/infra/docker から apps/lamp への相対パス
      dockerfile: ../../infra/docker/php/Dockerfile
    container_name: lamp-app
    ports:
      - 8080:80
    volumes:
      - ../../apps/lamp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lamp-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp_db
    volumes:
      - db-data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-pma
    ports:
      - "8081:80" # ← ブラウザアクセスは http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db-data:
